### PR TITLE
MPK01(keyboard K780), fix compatibility with Unifying receivers

### PR DESCRIPTION
**Pull request by ogay**
Fix compatibility with Unifying receivers (dongles) RQR12.xx (xx >= 08)
and RQR24.xx (xx >= 06).

Release:
   MPK01.03_B0024

### CODE REVIEW

**Comment by hughsie** [comment]
No metainfo file?

**Comment by ogay** [comment]
Add metainfo file and Makefile.

**Comment by hughsie** [comment]
With `<id compare="ge" version="0.9.2">org.freedesktop.fwupd</id>` changed to `<id compare="ge" version="0.9.5">org.freedesktop.fwupd</id>` (for the UFY change) it works great -- thanks!

**Comment by hughsie** [comment]
Also, it would be handy to have the "old" firmware on the LVFS too (even just in private/embargo), so that we can add an installed update and downgrade tests for fwupd. At the moment I'm just re-installing `MPK01.03_B0024` on itself, which doesn't seem a very helpful test.

**Comment by hughsie** [comment]
I'm assuming you're happy for me to upload both of these to the testing channel on the LVFS?

**Comment by xnlcasad** [comment]
Yes, please go ahead on the testing channel.

**Comment by hughsie** [comment]
Uploaded to private and embargo. Will push to testing once the installed tests for fwupd pass later today.

**Pull request merged**
