### PR TITLE
readme: fix typo, fix code blocks and misc improvements

### PR DESCRIPTION
**Pull request by FFY00**
Signed-off-by: Filipe Laíns <lains@archlinux.org>

### CODE REVIEW

**Review by mviredaz — COMMENTED** [review]
Based on Merriam-Webster (https://www.merriam-webster.com/dictionary/data#usage-1), I believe that the plural construction is more appropriate than the singular construction for "meta-data" in this context (i.e., "meta-data define").

**Comment by mviredaz** [comment]
Otherwise, I am agree with all other changes.

**Comment by FFY00** [comment]
I am conjugating the verb "define", the correct form is "it defines", "the meta-data defines".

**Comment by FFY00** [comment]
LGTM.

**Pull request merged**
